### ISSUE TITLE
What are your goals for The Silence?

### ISSUE THREAD

**Issue by bleachisback** [Gedan/the-silence#1]
I read your blurb on the Fen-blog about The Silence, but didn't quite understand where you're going with it. The general gist I got was that The Silence is supposed to be a separate game than TiTS, but still take place in the TiTS universe?

Which brings up the question: What are your current goals for The Silence, and how important are each of them? Also: How does The Silence differ from TiTS?

I'll happily pound away at a keyboard, but I'd like to know what I'm doing first =D

**Comment by Gedan** [comment]
Well, I was mainly giving you access so you can see exactly what I'm trying to do with the map system on a half-prototype-half-this-shit-is-awful kind of level. It does a bunch of stuff at the minute that we want to bring over to TiTS at _some_ point, and there's a bunch of "This actually seems to work a bit nicer" thrown in for good measure.

But yes, Silence takes place in the TiTS universe itself. The story is actually the backstory for a character that Savin is writing that will show up in/around Planet 4. We spun it off as a separate game for two main reasons:

It uses party combat. That's the whole point behind the lead character; she's a leader. Needs people to lead -> group versus group combat.

The "versus group" part is going to be important for TiTS, as that's on the agenda at some point too. It's giving me a good opportunity to try and throw some code around to figure out where the sticky areas are without nessecerily having to refactor it- it can be changed however it needs to be during a port-process, or rewritten from scratch and just lifting the lessons its taught by sheer virtue of existing.

I MAINLY wanted to fuck about with different ways of structuring the internals of the codebase though; Silence started off as an attempt to rebuild TiTS in HTML5 using Typescript (if you look at the early commits, there's a trace of Typescript still in there). I decided that, whilst I made SOME progress, Typescript is just too immature to be a solid foundation for something like this; the intention was to build a framework that could be used for other games, and then rebuild TiTS on top of it as a side-project, so there'd be a decent means of escaping from AS3/Flash/AIR if we felt we needed it. The reality though has proven that a JS based game suffers from ALL of the same problems that an AS3 based game does; just with a less-nice language behind the curtain. As much as I like to rag on AS3, at it's core it really does just boil down to JS with proper classes and packages/modules.
